# Problema 1

**Generar un nuevo dataset de vehículos y sus características.** Los datos incluirán información sobre vehículos como "Marca", "Modelo", "Año", "Precio", "Kilometraje", "Fecha de Registro". 100 registros

* Eliminar duplicados.
* Tratar valores nulos: rellenar o eliminar, dependiendo del contexto.
* Corregir tipos de datos.
* Eliminar espacios en blanco adicionales.
* Ordenar el DataFrame por el precio.
* Guardar el DataFrame limpio en un archivo CSV.

In [42]:
# Imports primero
import pandas as pd
import numpy as np
import random
import google.colab.drive as drive

drive.mount("/content/drive",force_remount=True)
TotalAutos = 100

Data = {
    "Nombre del Modelo":[f"Auto {i+1}" for i in range(TotalAutos)],
    "Marca":[f"Marca {random.randint(1,10)}" for i in range(TotalAutos)],
    "Año":[random.randint(1950,2020) for i in range(TotalAutos)],
    "Precio":[random.randint(20000,150000) for i in range(TotalAutos)],
    "Kilometraje":[random.randint(20000,150000) for i in range(TotalAutos)],
    "Fecha de Registro":[pd.Timestamp("1-1-2024") + pd.DateOffset(days=random.randint(0,365)) for i in range(TotalAutos)]
}

df = pd.DataFrame(Data)
print(df.head())

print("-----------------------------------------------------------------------------")

# Eliminar Duplicados
df.drop_duplicates(inplace=True)
print("Duplicados Eliminados")

print("-----------------------------------------------------------------------------")

# Ordenar el DataFrame por Precio
df_sorted = df.sort_values(by='Precio')

# Mostrar el DataFrame Ordenado
print(df_sorted)

print("-----------------------------------------------------------------------------")

# Generamos el archivo CSV
df.to_csv('/content/drive/MyDrive/Colab Notebooks/Examen 2 Ej 1.csv', index= False)
print("Archivo Generado")

Mounted at /content/drive
  Nombre del Modelo    Marca   Año  Precio  Kilometraje Fecha de Registro
0            Auto 1  Marca 4  1997  149596        50435        2024-02-24
1            Auto 2  Marca 1  2015   53355        73597        2024-03-05
2            Auto 3  Marca 8  2004   73335       132848        2024-09-11
3            Auto 4  Marca 3  1961  104516        33761        2024-07-29
4            Auto 5  Marca 9  2013  115181        48402        2024-02-01
-----------------------------------------------------------------------------
   Nombre del Modelo     Marca   Año  Precio  Kilometraje Fecha de Registro
74           Auto 75   Marca 4  2003   23753        37068        2024-09-28
5             Auto 6   Marca 8  1987   25631        97977        2024-12-10
40           Auto 41   Marca 9  1989   26041        66750        2024-02-04
19           Auto 20   Marca 6  1953   26377        33775        2024-12-01
57           Auto 58   Marca 6  1985   32881       141751        2024-04-20
..               ...       ...   ...     ...          ...               ...
62           Auto 63   Marca 4  2013  148932        80219        2024-09-29
53           Auto 54  Marca 10  1958  149005        29138        2024-11-21
98           Auto 99   Marca 1  1954  149416       134539        2024-06-08
0             Auto 1   Marca 4  1997  149596        50435        2024-02-24
75           Auto 76   Marca 3  1972  149695        28246        2024-06-22

[100 rows x 6 columns]
-----------------------------------------------------------------------------
Archivo Generado

# Problema 2

**Generar un nuevo dataset de libros en una librería.** Los datos incluirán información sobre libros como "Título", "Autor", "Género", "Precio", "Año de Publicación", "Número de Páginas", "Fecha de Adquisición". 100 registros

* Eliminar duplicados.
* Tratar valores nulos: rellenar o eliminar, dependiendo del contexto.
* Corregir tipos de datos.
* Eliminar espacios en blanco adicionales.
* Ordenar el DataFrame por el precio.
* Guardar el DataFrame limpio en un archivo CSV.

In [45]:
# Imports primero
import pandas as pd
import numpy as np
import random
import google.colab.drive as drive

drive.mount("/content/drive",force_remount=True)
TotalLibros = 100

Data = {
 "Titulo":[f"Libro {i+1}" for i in range(TotalLibros)],
 "Autor":[f"Marca {random.randint(1,10)}" for i in range(TotalLibros)],
 "Género":[random.choice(["Comedia","Horror","Fantasia","Amor","Accion","Suspenso","Sci-Fi"]) for i in range(TotalLibros)],
 "Precio":[random.randint(200,1500) for i in range(TotalLibros)],
 "Año de Publicación":[random.randint(1950,2020) for i in range(TotalLibros)],
 "Numero de Paginas":[random.randint(100,300) for i in range(TotalLibros)],
 "Fecha de Adquisición":[pd.Timestamp("1-1-2024") + pd.DateOffset(days=random.randint(0,365)) for i in range(TotalLibros)]
}

df = pd.DataFrame(Data)
print(df.head())

print("-----------------------------------------------------------------------------")

# Eliminar Duplicados
df.drop_duplicates(inplace=True)
print("Duplicados Eliminados")

df.

print("-----------------------------------------------------------------------------")

# Ordenar el dataframe por Precio
df_sorted = df.sort_values(by='Precio')

# Mostrar el DataFrame ordenado por precio
print(df_sorted)

print("-----------------------------------------------------------------------------")

# Generamos el archivo CSV
df.to_csv('/content/drive/MyDrive/Colab Notebooks/Examen 2 Ej 2.csv', index= False)
print("Archivo Generado")

Mounted at /content/drive
    Titulo    Autor    Género  Precio  Año de Publicación  Numero de Paginas  \
0  Libro 1  Marca 9      Amor     712                1953                298
1  Libro 2  Marca 2      Amor     722                2014                115
2  Libro 3  Marca 6    Horror     761                2010                135
3  Libro 4  Marca 6  Fantasia     988                2006                196
4  Libro 5  Marca 8   Comedia    1499                2006                267

  Fecha de Adquisición
0           2024-11-22
1           2024-06-27
2           2024-05-13
3           2024-10-14
4           2024-09-07
-----------------------------------------------------------------------------
Duplicados Eliminados
-----------------------------------------------------------------------------
      Titulo    Autor    Género  Precio  Año de Publicación  \
48  Libro 49  Marca 7  Suspenso     207                2018
6    Libro 7  Marca 4    Accion     210                1974
74  Libro 75  Marca 3    Horror     221                1979
60  Libro 61  Marca 1    Sci-Fi     236                1952
57  Libro 58  Marca 6    Horror     251                1996
..       ...      ...       ...     ...                 ...
72  Libro 73  Marca 7   Comedia    1479                2003
58  Libro 59  Marca 5  Fantasia    1479                1971
40  Libro 41  Marca 3    Horror    1489                1976
90  Libro 91  Marca 3    Horror    1489                1964
4    Libro 5  Marca 8   Comedia    1499                2006

    Numero de Paginas Fecha de Adquisición
48                134           2024-12-20
6                 144           2024-10-22
74                181           2024-11-14
60                125           2024-06-29
57                237           2024-08-05
..                ...                  ...
72                286           2024-05-03
58                158           2024-05-02
40                141           2024-06-16
90                197           2024-06-24
4                 267           2024-09-07

[100 rows x 7 columns]
-----------------------------------------------------------------------------
Archivo Generado

# Problema 3

**Generar un nuevo dataset de clientes en una tienda.** Los datos incluirán información sobre clientes como "ID Cliente", "Nombre", "Edad", "Correo Electrónico", "Fecha de Registro", "Total
Gastado".

* Eliminar duplicados.
* Tratar valores nulos: rellenar o eliminar, dependiendo del contexto.
* Corregir tipos de datos.
* Eliminar espacios en blanco adicionales.
* Ordenar el DataFrame por el total gastado.
* Guardar el DataFrame limpio en un archivo CSV.

In [44]:
# Imports primero
import pandas as pd
import numpy as np
import random
import google.colab.drive as drive

drive.mount("/content/drive",force_remount=True)
TotalClientes = 100

Data = {
 "ID del Cliente":range(1001,1101),
 "Nombre del Cliente":[f"Cliente {i+1}" for i in range(TotalClientes)],
 "Edad":[random.randint(19,50) for i in range(TotalClientes)],
 "Correo Electronico":[f"Correo{i+1}@gmail.com" for i in range(TotalClientes)],
 "Fecha de Registro":[pd.Timestamp("1-1-2024") + pd.DateOffset(days=random.randint(0,365)) for i in range(TotalClientes)],
 "Total Gastado":[random.randint(20,5000) for i in range(TotalClientes)]
}

df = pd.DataFrame(Data)
print(df.head())

print("-----------------------------------------------------------------------------")

# Eliminar Duplicados
df.drop_duplicates(inplace=True)
print("Duplicados Eliminados")

print("-----------------------------------------------------------------------------")

# Ordenar por total gastado
df_sorted = df.sort_values(by='Total Gastado')

# Mostrar el DataFrame ordenado por total gastado
print(df_sorted)

print("-----------------------------------------------------------------------------")

# Generamos el archivo CSV
df.to_csv('/content/drive/MyDrive/Colab Notebooks/Examen 2 Ej 3.csv', index= False)
print("Archivo Generado")

Mounted at /content/drive
   ID del Cliente Nombre del Cliente  Edad Correo Electronico  \
0            1001          Cliente 1    21  Correo1@gmail.com
1            1002          Cliente 2    27  Correo2@gmail.com
2            1003          Cliente 3    25  Correo3@gmail.com
3            1004          Cliente 4    42  Correo4@gmail.com
4            1005          Cliente 5    34  Correo5@gmail.com

  Fecha de Registro  Total Gastado
0        2024-06-14            944
1        2024-06-26           4887
2        2024-08-03           2292
3        2024-03-20           3913
4        2024-06-08            985
-----------------------------------------------------------------------------
Duplicados Eliminados
-----------------------------------------------------------------------------
    ID del Cliente Nombre del Cliente  Edad  Correo Electronico  \
76            1077         Cliente 77    23  Correo77@gmail.com
52            1053         Cliente 53    40  Correo53@gmail.com
15            1016         Cliente 16    29  Correo16@gmail.com
81            1082         Cliente 82    46  Correo82@gmail.com
96            1097         Cliente 97    27  Correo97@gmail.com
..             ...                ...   ...                 ...
71            1072         Cliente 72    21  Correo72@gmail.com
1             1002          Cliente 2    27   Correo2@gmail.com
14            1015         Cliente 15    26  Correo15@gmail.com
7             1008          Cliente 8    48   Correo8@gmail.com
93            1094         Cliente 94    50  Correo94@gmail.com

   Fecha de Registro  Total Gastado
76        2024-04-01             63
52        2024-08-19             89
15        2024-06-08            158
81        2024-05-08            162
96        2024-02-18            167
..               ...            ...
71        2024-01-01           4873
1         2024-06-26           4887
14        2024-10-11           4917
7         2024-12-20           4925
93        2024-12-10           4960

[100 rows x 6 columns]
-----------------------------------------------------------------------------
Archivo Generado